language: julia
os:
  - linux
env:
  - DATADEPS_ALWAYS_ACCEPT=true
julia:
  - nightly
  - 1.1
  - 1.0.3
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("TextAnalysis")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
