name = "GoogleDrive"
uuid = "91feb7a0-3508-11ea-1e8e-afea2c1c9a19"
authors = ["tejasvaidhyadev <iamtejasvaidhya@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
julia = "1.9"
Downloads = "1"
