name = "GoogleDrive"
uuid = "91feb7a0-3508-11ea-1e8e-afea2c1c9a19"
authors = ["tejasvaidhyadev <iamtejasvaidhya@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
